name: Secrets and Variables

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  showallemysecrets:
     runs-on: windows-latest
     #onprem windows runner:
     #runs-on:
     # labels: fhzengitrnr4 
     steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: run script   
        run: |
          write-host $env:USER
          write-host $env:PW
        env:
            USER: ${{ vars.username }}
            PW: ${{ secrets.sshpass }}